### ISSUE TITLE
Problem compiling on MacOS

### ISSUE THREAD

**Issue by jhuelsenbeck** [cddlib/cddplus#1]
I'm having real problems compiling the code, either using Xcode with compiler flags set as indicated and libraries included or using the makefile you have distributed. Specifically, I have problems with 'ext/pool_allocator.h' file not found and the bits directory for g++, too.

I really would like to get this code working for rational numbers!

**Comment by saraedum** [comment]
Should be fixed now. Feel free to reopen if it still does not work.

(See instructions in the README.)
